version: "3.2"
services:
  token_db:
    container_name: token_db
    image: postgres:13
    environment:
      POSTGRES_USER: stroka01
      POSTGRES_PASSWORD: token
      POSTGRES_DB: token_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always


volumes:
  pgdata:

