export enum MessagePatternEnum {
    'GET_USERS' = 'MESSAGE_GET_USERS',
    'GET_USER' = 'MESSAGE_GET_USER',
    'CREATE_USER' = 'MESSAGE_CREATE_USER',
    'UPDATE_USER' = 'MESSAGE_UPDATE_USER',
    'DELETE_USER' = 'MESSAGE_DELETE_USER',
}
