export enum UserLogsEnum {
    USER_INITIATED = 'User initiated',
    USER_RETRIEVING_ERROR = 'Error retrieving user',
    USER_RETRIEVED_SUCCESS = 'User retrieved successfully',
    USERS_INITIATED = 'Users initiated',
    USERS_RETRIEVING_ERROR = 'Error retrieving users',
    USERS_RETRIEVED_SUCCESS = 'Users retrieved successfully',
    USER_NOT_FOUND = 'User not found',
    USER_NOT_ALLOWED = 'User updating not allowed',
    USER_VALIDATION_INITIATED = 'User validation initiated',
    USER_VALIDATION_SUCCESS = 'User validation successful',
    USER_VALIDATION_FAILED = 'User validation failed',
    USER_VALIDATION_ERROR = 'Error validating user',
    USER_CREATION_INITIATED = 'User creation initiated',
    USER_CREATED = 'User created successfully',
    USER_CREATION_CONFLICT = 'User creation conflict',
    USER_CREATION_ERROR = 'Error creating user',
    USER_UPDATE_INITIATED = 'User update initiated',
    USER_UPDATED_SUCCESS = 'User updated successfully',
    USER_UPDATE_ERROR = 'Error updating user',
    USER_DELETION_INITIATED = 'User deletion initiated',
    USER_DELETED = 'User deleted successfully',
    USER_DELETION_ERROR = 'Error deleting user',
}
