version: "3.2"
services:
  user_db:
    container_name: user_db
    image: postgres:13
    environment:
      POSTGRES_USER: stroka01
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    restart: always

  token_db:
    container_name: token_db
    image: postgres:13
    environment:
      POSTGRES_USER: stroka01
      POSTGRES_PASSWORD: token
      POSTGRES_DB: token_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata_token:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net


volumes:
  pgdata_user:
  pgdata_token:


networks:
  rabbitmq_go_net:
    driver: bridge
