version: '3.0'

services:

  gateway:
    container_name: gateway
    build:
      dockerfile: ./gateway/Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8008:8008"
    command: yarn start:dev
    depends_on:
      - user_db
      - user
      - rabbitmq
    restart: always

  user:
    container_name: user
    build:
      dockerfile: ./user/Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8001:8001"
    command: yarn start:dev
    depends_on:
      - user_db
      - rabbitmq
    restart: always


  user_db:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "users"
      POSTGRES_USER: "user"
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5433:5433"
    expose:
      - "5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -p 5433
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net


networks:
  rabbitmq_go_net:
    driver: bridge
  user_db:
    driver: bridge

volumes:
  pgdata:
