FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app/mailer

COPY *.csproj ./
RUN dotnet restore

COPY ../engine/examples ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
