export enum MESSAGE_PATTERN {
    GET_USER_BY_ID = 'GET_USER_BY_ID',
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    TOKEN_CREATE = 'TOKEN_CREATE',
    TOKEN_DESTROY = 'TOKEN_DESTROY',
    USER_SEARCH_BY_CREDENTIALS = 'USER_SEARCH_BY_CREDENTIALS'
}
