export enum SERVICE {
    TOKEN = "TOKEN_SERVICE",
    USER = "USER_SERVICE",
    POST = "POST_SERVICE",
    PERMISSION = "PERMISSION_SERVICE",
    MAILER = "MAILER_SERVICE",
    ROLE = "ROLE_SERVICE",
}
